name: 'ğŸš€ Publish Plugin & Update Manifest'

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: ğŸ’¾ Install JPRM
        run: pip install jprm

      - name: ğŸ—ï¸ Generate Manifest
        env:
          JP_URL: https://github.com/${{ github.repository }}/releases/download
        run: |
          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # 1. Si le manifest.json n'existe pas, on l'initialise
          if [ ! -f "manifest.json" ]; then
            echo "âš ï¸ manifest.json introuvable. Initialisation du dÃ©pÃ´t..."
            jprm repo init . --url=${JP_URL}
          fi

          # 2. On ajoute le plugin au manifest (le premier point est le dossier du manifest, le second est le dossier du plugin)
          jprm repo add . .

      - name: ğŸš€ Commit & Push Manifest
        run: |
          git add manifest.json
          # Ne commit que s'il y a des changements
          git diff --staged --quiet || git commit -m "ğŸ¤– Update manifest.json for ${{ github.event.release.tag_name }}"
          git push origin master
