name: 'ğŸš€ Publish Plugin'

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ”§ Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      - name: ğŸ Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: ğŸ’¾ Install JPRM
        run: pip install jprm

      - name: ğŸ·ï¸ Update Version in build.yaml
        run: |
          VERSION=${{ github.event.release.tag_name }}
          VERSION=${VERSION#v}
          if [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            VERSION="${VERSION}.0"
          fi
          sed -i "s/version: .*/version: \"$VERSION\"/" build.yaml

      - name: ğŸ—ï¸ Build Plugin
        run: |
          dotnet publish Jellyfin.Plugin.Allocine/Jellyfin.Plugin.Allocine.csproj --configuration Release --output bin/publish
          cp bin/publish/Jellyfin.Plugin.Allocine.dll .

      - name: ğŸ“¦ Package Plugin
        run: |
          jprm --verbosity=debug plugin build . --output .
          mv *.zip Jellyfin.Plugin.Allocine.zip

      - name: â¬†ï¸ Upload Asset to Release
        uses: softprops/action-gh-release@v2
        with:
          files: Jellyfin.Plugin.Allocine.zip
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ“ Update Manifest.json
        env:
          JP_URL: https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          if [ ! -f "manifest.json" ]; then
            jprm repo init .
          fi

          jprm repo add --url=${JP_URL} . Jellyfin.Plugin.Allocine.zip

          git add manifest.json
          git diff --staged --quiet || git commit -m "ğŸ¤– Update manifest to ${{ github.event.release.tag_name }}"
          git push origin master
