name: 'ğŸš€ Publish Plugin & Update Manifest'

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: ğŸ’¾ Install JPRM
        run: pip install jprm

      - name: ğŸ—ï¸ Generate Manifest
        env:
          JP_URL: https://github.com/${{ github.repository }}/releases/download
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          if [ ! -f "manifest.json" ]; then
            echo "âš ï¸ Initialisation du manifest.json..."
            jprm repo init .
          fi

          jprm repo add --url=${JP_URL} . .

      - name: ğŸš€ Commit & Push Manifest
        run: |
          git add manifest.json
          git diff --staged --quiet || git commit -m "ğŸ¤– Update manifest.json for ${{ github.event.release.tag_name }}"
          git push origin master
